version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    network_mode: "host"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    network_mode: "host" 
  grafana:
    image: grafana/grafana:5.4.4
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    network_mode: "host"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/

