version: '3'
 
services:
  app:
    container_name: django-redis-app
    build:
      context: ./app
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
    networks:
      - django-celery-network
    
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8888"

    env_file:
      - ./.env
    depends_on:
      - db
 
  db:
    image: postgres:10-alpine
    container_name: django-redis-db
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - django-celery-network
  redis:
    container_name: django-redis
    image: redis:alpine
  celery:
    container_name: django-redis-celery
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    networks:
      - django-celery-network
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata:

  
networks:
  django-celery-network:
    driver: bridge
