version: '3'
 
services:
  django:
    container_name: django
    build:
      context: ./django
    ports:
      - "8888:8888"
    volumes:
      - ./django:/django
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8888"
    env_file:
      - ./.env
    depends_on:
      - db
 
  db:
    image: postgres:10-alpine
    container_name: db
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
#  redis:
#    container_name: redis
#    image: redis:alpine
#  celery:
#    container_name: celery
#    restart: always
#    build:
#      context: ./app
##      context: ./celery
#    command: celery -A app worker -l info
#    volumes:
#      - ./app:/app
##      - ./celery:/celery
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#      - redis
#      - app

volumes:
  pgdata: